### ISSUE TITLE
Use of uninitialized value $ENV{"HOME"} in concatenation (.) or string at Makefile.PL line 325

### ISSUE THREAD

**Issue by shawnlaffan** [PDLPorters/pdla-core#15]
This is a minor issue.  

One approach is to use ```"$ENV{HOMEDRIVE}$ENV{HOMEPATH}"/.perldl.conf"``` on windows, as that would not involve any extra modules.  

Let me know if you want a PR or already have a different fix in the works.

**Comment by mohawk2** [comment]
I believe the whole `perldl.conf` concept, whether local, or "personalised" by living in a home directory, is not a good idea at all, and my direction of travel is to eliminate it in favour of runtime config. This enhances scientific reproducibility as well. Therefore, let's not waste any time on this, but instead speed its elimination!

Once I've finished converting PDLA::Core to using `.pm`s with `Inline::Pdlapp` in a `__DATA__` section at the end, this will be next.

**Comment by shawnlaffan** [comment]
Makes sense to me.  Closing.
