### ISSUE TITLE
Look into a standard hook for updating pdldoc database

### ISSUE THREAD

**Issue by zmughal** [PDLPorters/pdla-core#2]
Replicate the functionality of [`add_doc.pl`](https://metacpan.org/source/MAGGIEXYZ/PDL-Stats-0.6.5/add_doc.pl) or calling PDL::Doc::add_module (as in [PDL::FFTW3](https://metacpan.org/source/DKOGAN/PDL-FFTW3-0.02.2/Makefile.PL#L91)). The former updates an entire tree while the later only does so for a single module.

For a complete list of modules on CPAN that use `PDL::Doc`, see this [query](http://grep.cpan.me/?q=PDL::Doc).

See also discussion at https://github.com/PDLPorters/pdl-io-gd/issues/3.

**Comment by mohawk2** [comment]
Proper PDL now has this as standard for both core and external modules in PDL::Core::Dev-generated `install` step. Closing, but please reopen/comment/open issue on proper PDL if you feel is needed!
